config/routes.rb
# frozen_string_literal: true

def for_model?(request, model)
  query = [
    ("_query_:\"" +
     ActiveFedora::SolrQueryBuilder
       .construct_query_for_ids([request.params[:id]]) +
     "\""),

    ActiveFedora::SolrQueryBuilder.construct_query_for_rel(
      [[:has_model, model.to_rdf_representation]]
    ),
  ].join(" AND ")
  results = ActiveFedora::SolrService.query query, fl: "has_model_ssim"
  results.present?
end

class CollectionRoutingConcern
  def matches?(request)
    for_model?(request, Collection)
  end
end

Rails.application.routes.draw do
  mount Blacklight::Engine => "/"
  mount Hydra::RoleManagement::Engine => "/"
  mount HydraEditor::Engine => "/"
  mount Qa::Engine => "/qa"
  mount Riiif::Engine => "/image-service", as: "riiif"

  root "welcome#index"

  get "welcome/about", as: "about"
  get "welcome/collection-usage-guidelines", as: "collection-usage-guidelines"
  get "welcome/using", as: "using"

  post "contact_us" => "contact_us#create", as: :contact_us
  get "contact_us" => "contact_us#new", as: :contact_us_form

  # new_user_session_path is hardcoded everywhere in Blacklight
  get "sign_in", to: "sessions#new", as: :new_user_session
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"

  get "404", to: "error#not_found"
  get "422", to: "error#server_error"
  get "500", to: "error#server_error"

  get "lib/:prot/:shoulder/:id" => "collections#show",
      constraints: CollectionRoutingConcern.new

  get "lib/:prot/:shoulder/:id" => "catalog#show", as: "catalog_ark"

  resources :local_authorities, only: :index

  get "authorities/agents/:id",
      to: "local_authorities#show",
      as: "agent"

  get "authorities/people/:id",
      to: "local_authorities#show",
      as: "person"

  get "authorities/groups/:id",
      to: "local_authorities#show",
      as: "group"

  get "authorities/organizations/:id",
      to: "local_authorities#show",
      as: "organization"

  get "authorities/topics/:id",
      to: "local_authorities#show",
      as: "topic"

  get "access/:id/edit", to: "access#edit", as: :edit_access
  post "access/:id/update", to: "access#update"
  post "access/:id/destroy", to: "access#destroy"
  post "access/:id/deactivate", to: "access#deactivate"

  concern :oai_provider, BlacklightOaiProvider::Routes.new

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  resource :catalog,
           only: [:index],
           as: "catalog",
           path: "/catalog",
           controller: "catalog" do
    concerns :oai_provider
    concerns :searchable
    concerns :range_searchable
  end

  # Make sure to define this concern before using it in
  # `curation_concerns_basic_routes' below
  concern :exportable, Blacklight::Routes::Exportable.new
  resources :solr_documents,
            only: [:show],
            path: "/catalog",
            controller: "catalog" do
    concerns :exportable
  end

  mount CurationConcerns::Engine, at: "/"
  curation_concerns_collections
  curation_concerns_basic_routes

  resources :embargoes, only: [:index, :edit, :destroy] do
    collection do
      patch :update
    end
  end

  resources :records, only: :destroy do
    get "new_merge", on: :member
    post "merge", on: :member
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete "clear"
    end
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  layout "curation_concerns", except: :index

  def index
    @background = images.sample
  end

  def about
    @page_title = "About"
  end

  def collection_usage_guidelines
    @page_title = "Collection Usage Guidelines"
  end

  def using
    @page_title = "FAQ"
  end

  def images
    @images ||= YAML.safe_load(
      File.read(Rails.root.join("config", "homepage.yml"))
    )
  rescue Errno::ENOENT
    [{}]
  end
end

app/views/welcome/_header_splash.html.erb
<header class="splash" style="background-image: url('<%= image_path(@background['image_path']) %>');">
  <%= render partial: '/user_util_links' %>

  <div class="flex-outer">
    <div class="flex-inner">
      <div class="large-logo">
        <a href="/" title="ADRL Homepage">
          <img src="<%= image_path("ADRL@1x.png") %>"
            srcset="<%= image_path("ADRL@2x.png") %> 2x"
            alt="Alexandria Digital Research Library">
        </a>
      </div>

      <div id="splash-search-bar">
        <%= render 'catalog/search_form' %>
      </div>

      <section id="browse-by">
        Or browse by
        <%= link_to 'Collection', collections_path %>,
        <%= link_to 'Contributor', facet_catalog_path(ObjectIndexer::ALL_CONTRIBUTORS_FACET) %>,
        <%= link_to 'Format', facet_catalog_path(Solrizer.solr_name('work_type_label', :facetable)) %>,
        or
        <%= link_to 'Topic', facet_catalog_path(Solrizer.solr_name('lc_subject_label', :facetable)) %>
      </section>

      <h2 class="blurb">Providing access to unique digital research materials from UC Santa Barbara Library</h2>

    </div>
  </div>

  <div class="background-metadata">
    <% unless @background.empty? %>
      <p class="background-metadata-title"><a href="/lib/<%= "#{@background['ark']}" %>" title="Record page"><%= @background['title'] %></a></p>
      <p class="background-metadata-collection">From the <a href="/collections/<%= @background['collection_id'] %>" title="Collection page"><%= @background['collection_title'] %></a></p>
    <% end %>
  </div>
</header>

app/views/welcome/about.html.erb
<div class="static">
  <h2> About the Alexandria Digital Research Library </h2>
  <div id="about_body">
    <p>The Alexandria Digital Research Library (ADRL) is <a href="http://www.library.ucsb.edu">UC Santa Barbara Library’s</a> home for collections of digital research materials, including images, text, streamed media, and numeric and spatial data. This comprehensive digital library, when complete, will provide access to millions of hidden digital research assets in UCSB Library’s possession, and serve as a single search access point.</p>
    <p>Many digital resources have already been added to ADRL and you can search for them now. Additional features and content are continually being added.</p>
    <p>ADRL builds on the expertise that UCSB developed in the 1990s with the <a href="https://www.library.ucsb.edu/geospatial/geospatial-collection-history">Alexandria Digital Library (ADL)</a>, an online repository for geospatial information. The new ADRL is more diverse, covering multiple disciplines and types of information.</p>
    <p>Materials in ADRL are subject to copyright and other restrictions, so a UCSB NetID and password may be required to view some materials.</p>
  </div>
</div>

app/views/welcome/collection_usage_guidelines.html.erb
<div class="static">
  <h2>Collection Usage Guidelines</h2>
  <p>The Alexandria Digital Research Library (ADRL) provides UCSB scholars, the people of California, and the global community, with digital collections to inspire and support their intellectual and creative endeavors.</p>
  <p>Materials in these collections may be protected by U.S. Copyright law (Title 17, U.S.C.). There may also be other use restrictions due to rights such as privacy or publicity, trademark, licensing, or gift or purchase agreements. While the UCSB Library has made reasonable effort to provide accurate information related to copyright and other restrictions, rights for some materials may be difficult to determine.</p>
  <p>Materials identified as public domain may be freely used. For all other materials, rights assessment is your responsibility. You must determine whether your use of any item requires the permission of any other person or entity, or whether you can exercise your <a href="http://www.library.ucsb.edu/sites/default/files/attachments/services/course-reserves/limitations-copyright-considerations/SCom_fairUseChecklist_final.pdf">fair use rights</a>.</p>
  <p>When citing or using material from the site, please provide our institution name (UCSB Library) and a link to the item, so that others can return to the original and learn more about it. You can then use your preferred style guide for formatting the citation. The Library of Congress provides additional guidance on <a href="http://www.loc.gov/teachers/usingprimarysources/citing.html">citing primary sources</a>.</p>
</div>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html class="welcome" lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
    <title>Alexandria Digital Research Library</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-RDKLZ6Y0NV"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-RDKLZ6Y0NV');
</script>
<body>
    <%= render '/flash_msg', layout: 'shared/flash_messages' %>
    <%= render 'welcome/header_splash' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/welcome/using.html.erb
<div class="static">

<h2>What is ADRL?</h2>
<p>ADRL, or the Alexandria Digital Research Library, contains collections of digital research materials held at <a href="http://www.library.ucsb.edu">UC Santa Barbara Library</a>, including images, text, streamed media, and numeric and spatial data.</p>
<p>Browse by <a href="http://alexandria.ucsb.edu/collections">collection</a> to find a complete list of current collections. New collections are being added all the time.</p>

<h2>Using ADRL</h2>
<ul>
<li><a href="#who-can-use-adrl">Who can use ADRL?</a></li>
<li><a href="#i-am-conducting-research.-can-you-help-me-find-more-information-about-my-topic">I am conducting research. Can you help me find more information about my topic?</a></li>
<li><a href="#i-found-a-particular-thesis-or-dissertation-in-adrl-that-i-want-to-read-but-access-is-restricted.-how-can-i-get-a-copy-of-this-dissertation">I found a particular thesis or dissertation in ADRL that I want to read, but access is restricted. How can I get a copy of this dissertation?</a></li>
<li><a href="#how-can-i-obtain-a-copy-of-an-image-that-i-found-in-adrl">How can I obtain a copy of an image that I found in ADRL?</a></li>
<li><a href="#where-can-i-find-geospatial-content-from-the-old-alexandria-digital-library-adl">Where can I find geospatial content from the old Alexandria Digital Library (ADL)?</a></li>
<li><a href="#how-do-i-cite-materials-that-i-find-in-adrl">How do I cite materials that I find in ADRL?</a></li>
<li><a href="#i-have-more-information-about-an-item-in-adrl.-how-can-i-provide-it">I have more information about an item in ADRL. How can I provide it?</a></li>
<li><a href="#what-is-the-technical-architecture-of-adrl">What is the technical architecture of ADRL?</a></li>
<li><a href="#how-can-i-report-a-problem-with-using-adrl">How can I report a problem with using ADRL?</a></li>
</ul>

<h3 id="who-can-use-adrl" class="question">Who can use ADRL?</h3>
<p>ADRL is publicly available and searchable to anyone. Materials in ADRL are subject to copyright and other restrictions, so a UCSB NetID and password may be required to view some materials.</p>
<h3 id="i-am-conducting-research.-can-you-help-me-find-more-information-about-my-topic" class="question">I am conducting research. Can you help me find more information about my topic?</h3>
<p>If you need help finding more information about a topic, or have a general research question, use our <a href="http://www.library.ucsb.edu/help/ask-librarian">Ask a Librarian</a> service to call, chat, or email a librarian, or to make an appointment.</p>
<h3 id="i-found-a-particular-thesis-or-dissertation-in-adrl-that-i-want-to-read-but-access-is-restricted.-how-can-i-get-a-copy-of-this-dissertation" class="question">I found a particular thesis or dissertation in ADRL that I want to read, but access is restricted. How can I get a copy of this dissertation?</h3>
<p>Access to a particular thesis or dissertation may be restricted for two reasons: the author may have restricted access via delayed release (embargo) or may have restricted online full-text access to UCSB only.</p>
<p>If the access restriction message reads “At the request of the author, this item is currently restricted via delayed access (embargo)," then the thesis or dissertation is currently embargoed, and may become available at a later date. Common embargo durations are 6 months, 1 year, or 2 years; however, longer embargo periods may be possible if approved by the University.</p>
<p>If the access restriction message reads “This item is restricted to on-campus access only” then the thesis or dissertation is not available free online to those outside UCSB. UCSB users can log in using your UCSB NetID to access these items from off-campus. Non-UCSB users can request a copy through your institution’s interlibrary loan service, <a href="http://www.proquest.com/products-services/dissertations/order-dissertation.html">purchase it from ProQuest</a>, or physically visit the UCSB Library and access it from a library computer.</p>
<h3 id="how-can-i-obtain-a-copy-of-an-image-that-i-found-in-adrl" class="question">How can I obtain a copy of an image that I found in ADRL?</h3>
<p>The majority of images in ADRL originate from UCSB Library’s <a href="http://www.library.ucsb.edu/special-collections">Department of Special Research Collections (SRC)</a>. Details about SRC’s reproduction fees and how to submit an online request for reproduction can be found at <a href="http://www.library.ucsb.edu/special-collections/research/copies_overview" class="uri">http://www.library.ucsb.edu/special-collections/research/copies_overview</a>.</p>
<h3 id="where-can-i-find-geospatial-content-from-the-old-alexandria-digital-library-adl" class="question">Where can I find geospatial content from the old Alexandria Digital Library (ADL)?</h3>
<p>All content from the old Alexandria Digital Library are accessible via the <a href="http://www.library.ucsb.edu/interdisciplinary-research-collaboratory">Interdisciplinary Research Collaboratory</a> at UCSB Library. We are in the process of adding as much of that data as possible to ADRL.</p>
<h3 id="how-do-i-cite-materials-that-i-find-in-adrl" class="question">How do I cite materials that I find in ADRL?</h3>
<p>This will vary depending on the type of resource and your preferred citation format. The following standard information should be included in the citation, regardless of format: creator, title, date, collection name, the institution (UC Santa Barbara Library), and the item’s URL. This information can be found with each item in ADRL.</p>
<p>Example:</p>
<pre>
London, Arthur. Soldiers and other onlookers at festival in Kumasi. Circa 1910-early 1920s. Arthur London / Gold Coast [Ghana] Photograph Collection. Department of Special Research Collections, UC Santa Barbara Library. http://alexandria.ucsb.edu/lib/ark:/48907/f3cf9ppb
</pre>
<p>Example:</p>
<pre>
Dryden, P. N. (2012). These Are a Few of My Favorite Things: The Cultural Meaning of the Tree (Doctoral dissertation). Retrieved from Alexandria Digital Research Library. (http://alexandria.ucsb.edu/lib/ark:/48907/f3000017)
</pre>
<h3 id="i-have-more-information-about-an-item-in-adrl.-how-can-i-provide-it" class="question">I have more information about an item in ADRL. How can I provide it?</h3>
<p>If you have additional information about the history or provenance of an item in our ADRL collections, please use our <a href="http://alexandria.ucsb.edu/contact_us">Contact Us</a> form to get in touch.</p>
<h3 id="what-is-the-technical-architecture-of-adrl" class="question">What is the technical architecture of ADRL?</h3>
<p>ADRL is a <a href="https://github.com/ucsblibrary/alexandria" title="ADRL source repository">locally developed digital library application</a> built using the Samvera technical framework. Samvera is based around several primary components, all of which are free and open source:</p>
<ul>
<li><p><a href="http://fedorarepository.org/about">Fedora</a>, a robust repository layer for the storage and management of digital objects;</p></li>
<li><p><a href="http://lucene.apache.org/solr/">Solr</a>, an indexing platform built on Apache Lucene, that provides fast access to information about repository objects and other resources;</p></li>
<li><p><a href="http://projectblacklight.org/">Blacklight</a>, a Ruby on Rails engine that provides a customizable discovery interface; and</p></li>
<li><p><a href="https://github.com/samvera/hydra-head/wiki">HydraHead</a>, a Ruby on Rails gem, or software library, that works with Active Fedora to provide CUD (create, update, and delete) functions for repository objects, along with other content management actions.</p></li>
</ul>
<p>ADRL includes <a href="https://github.com/samvera/curation_concerns">Curation Concerns</a>, a Ruby on Rails gem, that gives Samvera developers a common toolset to manage a wide range of complex digital objects. This gem provides a consistent way to manage various types of complex digital objects and their relationships such as manuscript collections, photos and printed ephemera, simple and complex audio and video recordings. Because the underlying relationships are described using the <a href="https://github.com/duraspace/pcdm/wiki">Portland Common Data Model (PCDM)</a>, these digital objects can be shared with non-Samvera systems using standard internet protocols for sharing linked data. The ADRL metadata model is expressed using the <a href="https://www.w3.org/TR/2014/REC-rdf11-concepts-20140225/">Resource Description Framework (RDF)</a>. Archival Resource Keys (ARKs), created using the California Digital Library’s <a href="http://ezid.cdlib.org">EZID service</a>, provide unique, persistent identifiers for repository objects.</p>
<p>ADRL was developed in partnership with <a href="https://curationexperts.com">Data Curation Experts (DCE)</a>.</p>
<p>More information about Samvera is available on <a href="https://samvera.org">the project homepage</a> and the <a href="https://wiki.duraspace.org/display/samvera/Technical+Framework+and+its+Parts">DuraSpace wiki</a>.</p>
<h3 id="how-can-i-report-a-problem-with-using-adrl" class="question">How can I report a problem with using ADRL?</h3>
<p>To report a problem or request further assistance, please use the <a href="http://alexandria.ucsb.edu/contact_us">Contact Us</a> form.</p>
</div>