config/routes.rb
# frozen_string_literal: true

def for_model?(request, model)
  query = [
    ("_query_:\"" +
     ActiveFedora::SolrQueryBuilder
       .construct_query_for_ids([request.params[:id]]) +
     "\""),

    ActiveFedora::SolrQueryBuilder.construct_query_for_rel(
      [[:has_model, model.to_rdf_representation]]
    ),
  ].join(" AND ")
  results = ActiveFedora::SolrService.query query, fl: "has_model_ssim"
  results.present?
end

class CollectionRoutingConcern
  def matches?(request)
    for_model?(request, Collection)
  end
end

Rails.application.routes.draw do
  mount Blacklight::Engine => "/"
  mount Hydra::RoleManagement::Engine => "/"
  mount HydraEditor::Engine => "/"
  mount Qa::Engine => "/qa"
  mount Riiif::Engine => "/image-service", as: "riiif"

  root "welcome#index"

  get "welcome/about", as: "about"
  get "welcome/collection-usage-guidelines", as: "collection-usage-guidelines"
  get "welcome/using", as: "using"

  post "contact_us" => "contact_us#create", as: :contact_us
  get "contact_us" => "contact_us#new", as: :contact_us_form

  # new_user_session_path is hardcoded everywhere in Blacklight
  get "sign_in", to: "sessions#new", as: :new_user_session
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"

  get "404", to: "error#not_found"
  get "422", to: "error#server_error"
  get "500", to: "error#server_error"

  get "lib/:prot/:shoulder/:id" => "collections#show",
      constraints: CollectionRoutingConcern.new

  get "lib/:prot/:shoulder/:id" => "catalog#show", as: "catalog_ark"

  resources :local_authorities, only: :index

  get "authorities/agents/:id",
      to: "local_authorities#show",
      as: "agent"

  get "authorities/people/:id",
      to: "local_authorities#show",
      as: "person"

  get "authorities/groups/:id",
      to: "local_authorities#show",
      as: "group"

  get "authorities/organizations/:id",
      to: "local_authorities#show",
      as: "organization"

  get "authorities/topics/:id",
      to: "local_authorities#show",
      as: "topic"

  get "access/:id/edit", to: "access#edit", as: :edit_access
  post "access/:id/update", to: "access#update"
  post "access/:id/destroy", to: "access#destroy"
  post "access/:id/deactivate", to: "access#deactivate"

  concern :oai_provider, BlacklightOaiProvider::Routes.new

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  resource :catalog,
           only: [:index],
           as: "catalog",
           path: "/catalog",
           controller: "catalog" do
    concerns :oai_provider
    concerns :searchable
    concerns :range_searchable
  end

  # Make sure to define this concern before using it in
  # `curation_concerns_basic_routes' below
  concern :exportable, Blacklight::Routes::Exportable.new
  resources :solr_documents,
            only: [:show],
            path: "/catalog",
            controller: "catalog" do
    concerns :exportable
  end

  mount CurationConcerns::Engine, at: "/"
  curation_concerns_collections
  curation_concerns_basic_routes

  resources :embargoes, only: [:index, :edit, :destroy] do
    collection do
      patch :update
    end
  end

  resources :records, only: :destroy do
    get "new_merge", on: :member
    post "merge", on: :member
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete "clear"
    end
  end
end

app/controllers/records_controller.rb
# frozen_string_literal: true

require "local_authority"

# Extends and customizes the RecordsController in hydra-editor
class RecordsController < ApplicationController
  load_resource only: [:destroy]
  load_and_authorize_resource only: [:new_merge, :merge]

  layout "curation_concerns"

  include RecordsControllerBehavior

  def destroy
    # Assume for now that the only type of records we can
    # delete using the UI are local authorities.
    authorize! :destroy, :local_authorities

    references = Record.references_for(@record)
    if references.empty?
      flash[:notice] = "Record \"#{@record.rdf_label.first}\" "\
                       "has been destroyed."
      @record.destroy
    else
      flash[:alert] = "Record \"#{@record.rdf_label.first}\" "\
                      "cannot be deleted because "\
                      "it is referenced by #{references.count} "\
                      "other #{"record".pluralize(references.count)}."
    end

    redirect_to local_authorities_path
  end

  # Displays the form to merge records
  def new_merge
    if LocalAuthority.local_authority?(@record)
      new_merge_form
    else
      flash[:alert] = "This record cannot be merged.  "\
                      "Only local authority records can be merged."
      redirect_to local_authorities_path
    end
  end

  def merge
    uri = fetch_merge_target
    if uri.present?
      merge_target_id = ActiveFedora::Base.uri_to_id(uri)
      MergeRecordsJob.perform_later(
        @record.id,
        merge_target_id,
        current_user.user_key
      )
      flash[:notice] = "A background job has been queued to merge the records."
      redirect_to local_authorities_path
    else
      flash[:alert] = "Error:  Unable to queue merge job.  "\
                      "Please fill in all required fields."
      new_merge_form
      render :new_merge
    end
  end

  protected

    def redirect_after_create
      redirect_after_update
    end

    def redirect_after_update
      if resource.class.include? LocalAuthorityBase
        polymorphic_url(resource)
      else
        solr_document_path(resource.id)
      end
    end

  private

    # Override method from hydra-editor to insert record origin
    def set_attributes
      super
      if resource.respond_to?(:record_origin) && resource.new_record?
        resource.record_origin << "#{Time.now.utc.to_s(:iso8601)} "\
                                  "Record originated in ADRL"
      end
      resource.attributes
    end

    def new_merge_form
      form_class = @record.is_a?(Agent) ? NameMergeForm : SubjectMergeForm
      @form = form_class.new(@record)
    end

    def fetch_merge_target
      attrs = params.select do |key|
        key.match(/^.*merge_target_attributes$/)
      end.values.first || {}

      attrs.fetch("0", {}).fetch("id", nil)
    end
end

app/views/records/_agent_form.html.erb
<%= simple_form_for form, url: record_form_action_url(form), html: { class: 'editor' } do |f| %>

  <%= hidden_field_tag :type, params[:type] %>

  <div id="descriptions_display">
    <%= render 'records/form_header' %>

    <div class="well">
      <% (f.object.terms).each do |term| %>
        <%= render_edit_field_partial(term, f: f) %>
      <% end %>
    </div>
  </div>

  <div class="form-actions">
    <div class="primary-actions">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to t(:'helpers.action.cancel'), main_app.root_path, class: 'btn btn-link' %>
    </div>
  </div>

<% end %>

app/views/records/_form.html.erb
<%= simple_form_for form, url: record_form_action_url(form), html: { class: 'editor' } do |f| %>
  <div id="descriptions_display">
    <%= render 'records/form_header' %>
    <div class="well">
      <%= render_edit_field_partial(:title, f: f) %>
      <%= render_edit_field_partial(:alternative, f: f) %>
      <%= f.input :ark, disabled: true %>
      <% (f.object.terms - [:title, :alternative]).each do |term| %>
        <%= render_edit_field_partial(term, f: f) %>
      <% end %>
      <%= f.input :record_origin, disabled: true, as: :multi_value_readonly %>
    </div> <!-- /well -->
  </div>
  <%= hidden_field_tag :type, params[:type] %>
  <div class="form-actions">
    <div class="primary-actions">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to t(:'helpers.action.cancel'), main_app.root_path, class: 'btn btn-link' %>
    </div>
  </div>
<% end %>

app/views/records/_form_selector.html.erb
<% if LocalAuthority.local_name_authority?(@record) %>
  <%= render partial: 'records/agent_form' %>
<% elsif LocalAuthority.local_subject_authority?(@record) %>
  <%= render partial: 'records/topic_form' %>
<% else %>
  <%= render partial: 'records/form' %>
<% end %>

app/views/records/_form_terms_footer.html.erb
<div class="date-time-fields" role="tabpanel">

  <h3>Dates &amp; Times</h3>

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#created" aria-controls="created" role="tab" data-toggle="tab">Date Created</a></li>
    <li role="presentation"><a href="#issued" aria-controls="issued" role="tab" data-toggle="tab">Issued</a></li>
    <li role="presentation"><a href="#other" aria-controls="other" role="tab" data-toggle="tab">Other</a></li>
    <li role="presentation"><a href="#copyrighted" aria-controls="copyrighted" role="tab" data-toggle="tab">Copyrighted</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="created">
      <div class="date-editor">
        <%= f.input :created, as: :time_span, wrapper_html: {class: 'time-span form-group', data: {name: :created}}, input_html: { class: 'form-control' }, required: f.object.required?(:created) %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="issued">
      <div class="date-editor">
        <%= f.input :issued, as: :time_span, wrapper_html: {class: 'time-span form-group', data: {name: :issued}}, input_html: { class: 'form-control' }, required: f.object.required?(:issued) %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="other">
      <div class="date-editor">
        <%= f.input :date_other, as: :time_span, wrapper_html: {class: 'time-span form-group', data: {name: :date_other}}, input_html: { class: 'form-control' }, required: f.object.required?(:date_other) %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="copyrighted">
      <div class="date-editor">
        <%= f.input :date_copyrighted, as: :time_span, wrapper_html: {class: 'time-span form-group', data: {name: :date_copyrighted}}, input_html: { class: 'form-control' }, required: f.object.required?(:date_copyrighted) %>
      </div>
    </div>
  </div>

</div>

app/views/records/_topic_form.html.erb
<%= simple_form_for form, url: record_form_action_url(form), html: { class: 'editor' } do |f| %>

  <%= hidden_field_tag :type, params[:type] %>

  <div id="descriptions_display">
    <%= render 'records/form_header' %>

    <div class="well">
      <% (f.object.terms).each do |term| %>
        <%= render_edit_field_partial(term, f: f) %>
      <% end %>
    </div>
  </div>

  <div class="form-actions">
    <div class="primary-actions">
      <%= f.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to t(:'helpers.action.cancel'), main_app.root_path, class: 'btn btn-link' %>
    </div>
  </div>

<% end %>

app/views/records/edit.html.erb
<h1><%= edit_record_title %></h1>
<%= render partial: 'records/form_selector' %>

app/views/records/new.html.erb
<h1><%= new_record_title %></h1>
<%= render partial: 'records/form_selector' %>

app/views/records/new_merge.html.erb
<h1> Merge Record: <%= @form.title %> </h1>

<p> Merge this record into another record.  All references to this record will be updated, and this record will be deleted. </p>

<%= simple_form_for @form, url: merge_record_path(@record), html: { class: 'editor', method: :post } do |f| %>

  <div class='well'>
    <noscript> <h3> This form will not work without Javascript enabled </h3> </noscript>

    <% (f.object.required_fields).each do |field_name| %>
      <%= f.input field_name, label: 'Merge Into', as: :controlled_vocabulary_select, input_html: { class: 'form-control' }, required: true %>
    <% end %>
  </div>

  <div class='form-actions'>
    <div class='primary-actions'>
      <%= f.submit 'Merge', class: 'btn btn-primary', data: { confirm: 'Are you sure you want to merge and delete this record?' } %>
    </div>
  </div>
<% end %>