config/routes.rb
# frozen_string_literal: true

def for_model?(request, model)
  query = [
    ("_query_:\"" +
     ActiveFedora::SolrQueryBuilder
       .construct_query_for_ids([request.params[:id]]) +
     "\""),

    ActiveFedora::SolrQueryBuilder.construct_query_for_rel(
      [[:has_model, model.to_rdf_representation]]
    ),
  ].join(" AND ")
  results = ActiveFedora::SolrService.query query, fl: "has_model_ssim"
  results.present?
end

class CollectionRoutingConcern
  def matches?(request)
    for_model?(request, Collection)
  end
end

Rails.application.routes.draw do
  mount Blacklight::Engine => "/"
  mount Hydra::RoleManagement::Engine => "/"
  mount HydraEditor::Engine => "/"
  mount Qa::Engine => "/qa"
  mount Riiif::Engine => "/image-service", as: "riiif"

  root "welcome#index"

  get "welcome/about", as: "about"
  get "welcome/collection-usage-guidelines", as: "collection-usage-guidelines"
  get "welcome/using", as: "using"

  post "contact_us" => "contact_us#create", as: :contact_us
  get "contact_us" => "contact_us#new", as: :contact_us_form

  # new_user_session_path is hardcoded everywhere in Blacklight
  get "sign_in", to: "sessions#new", as: :new_user_session
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"

  get "404", to: "error#not_found"
  get "422", to: "error#server_error"
  get "500", to: "error#server_error"

  get "lib/:prot/:shoulder/:id" => "collections#show",
      constraints: CollectionRoutingConcern.new

  get "lib/:prot/:shoulder/:id" => "catalog#show", as: "catalog_ark"

  resources :local_authorities, only: :index

  get "authorities/agents/:id",
      to: "local_authorities#show",
      as: "agent"

  get "authorities/people/:id",
      to: "local_authorities#show",
      as: "person"

  get "authorities/groups/:id",
      to: "local_authorities#show",
      as: "group"

  get "authorities/organizations/:id",
      to: "local_authorities#show",
      as: "organization"

  get "authorities/topics/:id",
      to: "local_authorities#show",
      as: "topic"

  get "access/:id/edit", to: "access#edit", as: :edit_access
  post "access/:id/update", to: "access#update"
  post "access/:id/destroy", to: "access#destroy"
  post "access/:id/deactivate", to: "access#deactivate"

  concern :oai_provider, BlacklightOaiProvider::Routes.new

  concern :searchable, Blacklight::Routes::Searchable.new
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  resource :catalog,
           only: [:index],
           as: "catalog",
           path: "/catalog",
           controller: "catalog" do
    concerns :oai_provider
    concerns :searchable
    concerns :range_searchable
  end

  # Make sure to define this concern before using it in
  # `curation_concerns_basic_routes' below
  concern :exportable, Blacklight::Routes::Exportable.new
  resources :solr_documents,
            only: [:show],
            path: "/catalog",
            controller: "catalog" do
    concerns :exportable
  end

  mount CurationConcerns::Engine, at: "/"
  curation_concerns_collections
  curation_concerns_basic_routes

  resources :embargoes, only: [:index, :edit, :destroy] do
    collection do
      patch :update
    end
  end

  resources :records, only: :destroy do
    get "new_merge", on: :member
    post "merge", on: :member
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete "clear"
    end
  end
end

app/controllers/catalog_controller.rb
# frozen_string_literal: true

class CatalogController < ApplicationController
  include BlacklightRangeLimit::ControllerOverride
  include CurationConcerns::CatalogController
  include Hydra::Controller::ControllerBehavior
  include BlacklightOaiProvider::Controller

  # enforce_show_permissions is from hydra-access-controls gem
  before_action :enforce_show_permissions, only: :show

  def enforce_show_permissions(_opts = {})
    permissions = current_ability.permissions_doc(params[:id])
    return if can?(:discover, permissions)

    raise Hydra::AccessDenied.new(
      "You do not have sufficient access privileges to access this document.",
      :discover, params[:id]
    )
  end

  rescue_from Blacklight::Exceptions::RecordNotFound do |e|
    logger.error "(Blacklight::Exceptions::RecordNotFound): #{e.inspect}"
    @unknown_type = "Document"
    @unknown_id = params[:id]
    render "errors/not_found", status: 404
  end

  rescue_from Blacklight::Exceptions::InvalidSolrID do |e|
    logger.error e
    @unknown_type = "Document"
    @unknown_id = params[:id]
    render "errors/not_found", status: 404
  end

  # Turn off SMS
  # https://groups.google.com/d/msg/blacklight-development/l_zHRF_GQc8/_qUUbJSs__YJ
  CatalogController.blacklight_config.show.document_actions.delete(:sms)

  # TODO: re-implement this functionality
  # https://github.library.ucsb.edu/ADRL/alexandria/pull/29
  # https://help.library.ucsb.edu/browse/DIGREPO-504
  CatalogController.blacklight_config.show.document_actions.delete(:email)
  CatalogController.blacklight_config.show.document_actions.delete(:citation)

  add_show_tools_partial(:edit, partial: "catalog/edit", if: :editor?)
  add_show_tools_partial(:download, partial: "catalog/download")
  add_show_tools_partial(:access,
                         partial: "catalog/access",
                         if: :show_embargos_link?)

  configure_blacklight do |config|
    config.search_builder_class = SearchBuilder
    config.view.gallery.partials = [:index_header, :index]
    config.view.slideshow.partials = [:index]
    config.view.slideshow.slideshow_method = :choose_image

    config.oai = {
      provider: {
        repository_name: Settings.oai_repository_name,
        repository_url: Settings.oai_repository_url,
        record_prefix: Settings.oai_record_prefix,
        admin_email: Rails.application.secrets.oai_admin_email,
      },
      document: {
        limit: 25,
        set_fields: [
          { label: "Collection", solr_field: "collection_label_ssim" },
        ],
      },
    }

    # This controls which partials are used, and in what order, for
    # each record type.  E.g., for an AudioRecording we will render
    #
    # - _breadcrumbs_audio_recording.html.erb
    # - _title_audio_recording.html.erb
    # - _media_audio_recording.html.erb
    # - _show_audio_recording.html.erb
    # - _downloads_audio_recording.html.erb
    #
    # falling back to _title_default etc. in each case.
    config.show.partials = [
      :breadcrumbs,
      :title,
      :media,
      :show,
      :downloads,
    ]

    # config.show.tile_source_field = :content_metadata_image_iiif_info_ssm
    # config.show.partials.insert(1, :openseadragon)

    config.default_solr_params = {
      qf: %w[
        accession_number_tesim
        alternative_tesim
        author_tesim
        keywords_tesim
        lc_subject_label_tesim
        location_label_tesim
        title_tesim
        all_text_timv
      ].join(" "),
      wt: "json",
      qt: "search",
      rows: 10,
    }

    # solr field configuration for search results/index views
    config.index.title_field = solr_name("title", :stored_searchable)
    config.index.display_type_field = "has_model_ssim"
    config.index.thumbnail_field = ObjectIndexer.thumbnail_field

    # Solr fields that will be treated as facets by the blacklight application
    #
    # The ordering of the field names is the order of the display.
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    #
    # * If left unset, then all facet values returned by solr will be
    #   displayed (not always all results in Fedora; see
    #   https://github.library.ucsb.edu/ADRL/alexandria/issues/13)
    #
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    #   solr request, with actual solr request being +1 your configured limit --
    #   you configure the number of items you actually want _tsimed_ in a page.
    #
    # * If set to 'true', then no additional parameters will be sent
    #   to solr, but any 'sniffed' request limit parameters will be
    #   used for paging, with paging at requested limit -1. Can sniff
    #   from facet.limit or f.specific_field.facet.limit solr request
    #   params. This 'true' config can be used if you set limits in
    #   :default_solr_params, or as defaults on the solr side in the
    #   request handler itself. Request handler defaults sniffing
    #   requires solr requests to be made with "echoParams=all", for
    #   app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    config.add_facet_field solr_name("work_type_label", :facetable),
                           label: "Format", limit: true

    config.add_facet_field solr_name("collection_label", :symbol),
                           label: "Collection", limit: true

    config.add_facet_field ObjectIndexer::ALL_CONTRIBUTORS_FACET,
                           label: "Contributor", limit: true

    config.add_facet_field solr_name("lc_subject_label", :facetable),
                           label: "Topic", limit: 20

    config.add_facet_field solr_name("location_label", :facetable),
                           label: "Place", limit: true

    config.add_facet_field solr_name("form_of_work_label", :facetable),
                           label: "Genre", limit: true

    config.add_facet_field ObjectIndexer::FACETABLE_YEAR,
                           label: "Date", range: true

    config.add_facet_field solr_name("language", :facetable),
                           label: "Language", limit: true

    config.add_facet_field solr_name("department", :facetable),
                           label: "Academic Department", limit: true

    config.add_facet_field solr_name("sub_location", :facetable),
                           label: "Library Location", limit: true

    config.add_facet_field solr_name("license_label", :facetable),
                           label: "Rights", limit: true

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!
    # use this instead if you don't want to query facets marked :show=>false
    # config.default_solr_params[:'facet.field'] =
    #   config.facet_fields.select { |_k, v| v[:show] != false }.keys

    # Solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    config.add_index_field solr_name("work_type_label", :stored_searchable),
                           label: "Format"

    config.add_index_field solr_name("collection_label", :symbol),
                           label: "Collection"

    config.add_index_field ObjectIndexer::ALL_CONTRIBUTORS_LABEL,
                           label: "Contributors",
                           if: :show_contributors?

    config.add_index_field solr_name("author_label", :stored_searchable),
                           label: "Author", if: :show_author?

    config.add_index_field solr_name("created", :displayable),
                           label: "Creation Date"

    config.add_index_field solr_name("issued", :displayable),
                           label: "Issued Date"

    config.add_index_field solr_name("description", :stored_searchable),
                           label: "Summary",
                           if: :collection?

    # Solr fields to be displayed in the show (item-level) view
    #   The ordering of the field names is the order of the display
    Metadata::RELATIONS.keys.each do |key|
      config.add_show_field solr_name("#{key}_label", :stored_searchable),
                            label: key.to_s.titleize,
                            link_to_search: "all_contributors_label_sim"
    end

    config.add_show_field solr_name("alternative", :stored_searchable),
                          label: "Variant Title"

    config.add_show_field solr_name("place_of_publication", :stored_searchable),
                          label: "Place of Publication"

    config.add_show_field solr_name("publisher", :stored_searchable),
                          label: "Publisher"

    config.add_show_field solr_name("created", :displayable),
                          label: "Creation Date"

    config.add_show_field solr_name("issued", :displayable),
                          label: "Issued Date"

    config.add_show_field solr_name("date_other", :displayable),
                          label: "Other Date"

    config.add_show_field solr_name("language", :stored_searchable),
                          label: "Language"

    config.add_show_field solr_name("lc_subject_label", :stored_searchable),
                          label: "Topics",
                          link_to_search: "lc_subject_label_sim"

    config.add_show_field solr_name("marc_subjects", :stored_searchable),
                          label: "Topics",
                          link_to_search: "marc_subjects_sim"

    config.add_show_field solr_name("location_label", :stored_searchable),
                          label: "Places",
                          link_to_search: "location_label_sim"

    config.add_show_field(
      solr_name("keywords", :stored_searchable),
      label: "Keywords",
      separator_options: {

app/views/catalog/_access_denied.html.erb
  <table class="table table-bordered" id="downloads">
    <tbody>
      <tr>
        <td class="access-row denied" colspan="2">Access: <%= t(".#{document.admin_policy_id}") %></td>
      </tr>
    </tbody>
  </table>

app/views/catalog/_deep_zoom.html.erb
<% if document.file_sets.present? %>
  <div class="row zoom">
    <%= openseadragon_picture_tag(
      document["file_set_iiif_manifest_ssm"],
      { data: { openseadragon: { sequenceMode: true, showReferenceStrip: true } } }
    ) %>
  </div>
<% end %>

app/views/catalog/_document.html.erb
<li id="document_<%= document.to_param %>" class="<%= render_document_class document %>" itemscope itemtype="<%= document.itemtype %>">
  <%= render_document_partials document, blacklight_config.view_config(document_index_view_type).partials, document_counter: document_counter %>
</li>

app/views/catalog/_download.html.erb
<% if document %>
  <%= link_to 'Download Metadata', solr_document_path(document, format: :ttl) %>
<% end %>

app/views/catalog/_downloads_etd.html.erb
<% if document.file_sets.present? && document.file_sets.any? { |fs| fs["original_filename_ss"].present? } %>
  <% if can?(:read, document) %>
    <%= render 'files', document: document %>
  <% else %>
    <%= render 'access_denied', document: document %>
  <% end %>
<% end %>

app/views/catalog/_index_component_maps.html.erb
<% component_maps = document.component_maps %>
<% index_maps = document.index_maps.reject { |i| i["square_thumbnail_url_ssm"].nil? } %>

<div class="map-tray">
<% if index_maps.present? %>
  <div class="col-md-3">
    <h3>Index Maps</h3>
    <ul>
    <% index_maps.each_with_index do |map, i| %>
      <% shoulder = params["shoulder"] || map["identifier_ssm"].first.match(%r{ark:\/([^\/]+)\/.*})[1] %>
      <li>
        <%=
        link_to(
          image_tag(map["square_thumbnail_url_ssm"].first),
          main_app.catalog_ark_path("ark:", shoulder, map.id),
          :id => "indexmap#{i}"
        )
        %> <%=
        link_to(
          content_tag(:span, map["title_tesim"].first, class: "tray-label"),
          main_app.catalog_ark_path("ark:", shoulder, map.id)
        )
        %>
      </li>
    <% end %>
  </ul></div>
<% end %>

<% if component_maps.present? %>
  <% # If there are no index maps, take up the whole width of the screen
    if index_maps.count == 0 %>
      <div class="col-md-12">
  <% # If there is a single index map, split it 3/9
    elsif index_maps.count == 1 %>
      <div class="col-md-9">
  <% end %>
  <%
     self_index = component_maps.index { |cm| cm.id == document.id }
     counter_string = if self_index.is_a? Integer
       " (viewing #{self_index + 1} of #{component_maps.count})"
     end
  %>
  <h3>Map Sheets<%= counter_string %></h3>
  <ul>
    <%
    component_maps.each_with_index do |comp, i| %>
      <% self_map = document.id == comp.id %>
      <% shoulder = params["shoulder"] || comp["identifier_ssm"].first.match(%r{ark:\/([^\/]+)\/.*})[1] %>
      <li>
        <%=
        img = image_tag(comp["square_thumbnail_url_ssm"].first,
                        class: "#{'self-map' if self_map}")
        # don't link to yourself
        if self_map
          img
        else
          link_to(img, main_app.catalog_ark_path("ark:", shoulder, comp.id))
        end
        %> <%=
           span = content_tag(:span,
                              comp["alternative_tesim"].first,
                              class: "tray-label#{' self-map' if self_map}")
           # don't link to yourself
           if self_map
             span
           else
             link_to(span, main_app.catalog_ark_path("ark:", shoulder, comp.id))
           end
        %>
      </li>
    <% end %>
  </ul></div>
<% end %>
</div>

app/views/catalog/_index_header_default.html.erb
_index_header_list_default.html.erb

app/views/catalog/_media_audio_recording.html.erb
<% document.file_sets.each do |fs| %>
  <div class="audio-player">
    <h3><%= fs.title.first %></h3>
    <%= media_display(fs) %>
  </div>
<% end %>

app/views/catalog/_media_index_map.html.erb
<%= render (can_view_full_image?(document.id) ? "deep_zoom" : "media_image"), document: document %>

app/views/catalog/_media_scanned_map.html.erb
<%= render (can_view_full_image?(document.id) ? "deep_zoom" : "media_image"), document: document %>

app/views/catalog/_show_index_map.html.erb
<%= render 'index_component_maps', document: document %>
<%= render 'show_default', document: document %>
<%= render 'map_set_attributes', document: document %>

app/views/catalog/_show_map_set.html.erb
<%= render 'index_component_maps', document: document %>
<%= render 'show_default', document: document %>
<%= render 'map_set_attributes', document: document %>

app/views/catalog/_title_default.html.erb
<% if document['description_tesim'].present? %>
  <%= content_for :head do %>
    <meta name="description" content="<%= document['description_tesim'].first.split('\n\n').first %>">
  <% end %>
<% end %>

<div class="row">
  <%= render 'show_header_default', document: document %>
</div>